<form action="/users" method="post">
  <div>
    <label>
        Nickname
      <input type="text" name="user[nickname]">
    </label>
  </div>
  <div>
    <label>
      Email
      <input type="email" required name="user[email]">
    </label>
    </div>
  <div>
    <label>
        Пароль
    <input type="password" required name="user[password]">
    </label>
    </div>
  <div>
    <label>
        Подтверждение пароля
    <input type="password" required name="user[passwordConfirmation]">
    </label>
  </div>
  <div>
    <label>
      Город
      <select name="user[city]">
        <option value="1">Минск</option>
        <option value="2">Брест</option>
      </select>
    </label>
  </div>
  <input type="submit" value="Sign Up">
</form>
